### ISSUE TITLE
I cant see the Country

### ISSUE THREAD

**Issue by SwezyTryhard** [Illegal-Services/GTA-V-Session-Sniffer#1]

**Comment by Illegal-Services** [comment]
Hello, that's not really an issue, I think you get a "None" value on the countrys right.

So to fiix that it's a bit complicated, I still have to add a youtube tutorial on how to make this functionality works.

I'm currently busy with other projects, but on next version, I'll add this video, if you still wanna give a shot manually yourself, basically you gotta install wireshark, and in wireshark settings set the MaxMind DB. It's not easy for those who don't know how to do it tbh.

**Comment by Illegal-Services** [comment]
So I assumed waiting for a new update to get an already existing feature is dumb, so I just recorded the video here in this issue.
Here is the tutorial:

https://user-images.githubusercontent.com/62464560/213780359-c7171f62-cf44-4ee9-81ea-9200df8222a5.mp4

**Comment by Illegal-Services** [comment]
@SwezyTryhard  So I assumed waiting for a new update to get an already existing feature is dumb, so I just recorded the video here in this issue.
Here is the tutorial:
https://user-images.githubusercontent.com/62464560/213780359-c7171f62-cf44-4ee9-81ea-9200df8222a5.mp4
