### ISSUE TITLE
Issue with modules

### ISSUE THREAD

**Issue by Stefantie32** [Illegal-Services/GTA-V-Session-Sniffer#4]
I seem to have issues importing line 13 and 14 (from Modules.capture.sync_capture import PacketCapture, Packet,TSharkNotFoundException, from Modules.oui_lookup.oui_lookup import MacLookup)
I need help fixing this issue

**Comment by Illegal-Services** [comment]
Are you using the released version with the executable version or are you running from source?

**Comment by Stefantie32** [comment]
If im correct yes

**Comment by Illegal-Services** [comment]
If you are using the executable version I don't see a problem where this would happen

**Comment by Illegal-Services** [comment]
make sure you installed wireshark and npcap before executing

**Comment by Stefantie32** [comment]
this is what appears 
ModuleNotFoundError: No module named 'Modules'
![Screenshot 2024-06-10 174343](https://github.com/Illegal-Services/GTA-V-Session-Sniffer/assets/167341952/499c35df-1e4e-4317-9939-2136650b19b0)

**Comment by Stefantie32** [comment]
what modules do i have to install can you send me the pip code for the cmd

**Comment by Illegal-Services** [comment]
there is no pip, it's internal

**Comment by Stefantie32** [comment]
i will try

**Comment by Stefantie32** [comment]
i downloaded the folder but it seems to be no fix

**Comment by Illegal-Services** [comment]
why are you opening my code anyways

**Comment by Stefantie32** [comment]
it said it was an open file and ive been looking for something like this
