### ISSUE TITLE
ARP PS5

### ISSUE THREAD

**Issue by ege-art** [Illegal-Services/GTA-V-Session-Sniffer#5]
When I connect to my PS5 with ARP and start a session, I don't get any players to show up in the list. I don't know if this is supposed to be like that? Or does this only work when the PS5 is directly connected to  the pc to get packages?

**Comment by Illegal-Services** [comment]
> When I connect to my PS5 with ARP and start a session, I don't get any players to show up in the list. I don't know if this is supposed to be like that? Or does this only work when the PS5 is directly connected to the pc to get packages?

Mhmm to  be honest with you it sounds like you follow each steps correctly (choosing ARP for console), make sure you're scanning from the right network interface, that the mac/ip address of the console matches the one you're going to scan on the program

**Comment by ege-art** [comment]
> > When I connect to my PS5 with ARP and start a session, I don't get any players to show up in the list. I don't know if this is supposed to be like that? Or does this only work when the PS5 is directly connected to the pc to get packages?
> 
> 
> 
> Mhmm to  be honest with you it sounds like you follow each steps correctly (choosing ARP for console).
> 
> I guess make sure you're scanning from the right network interface, that the mac/ip addresses from that one matches the console one too.

Thanks for your fast response, I'm new to this, how do I do that? And btw my ps won't show up until I ping it's ip address

**Comment by ege-art** [comment]
Now I understand, I'll try it and text here if it worked or not

**Comment by Illegal-Services** [comment]
> "my ps won't show up until I ping it's ip address"

Curious, also my script won't update the network interfaces in real time, you need to restart the script if something technically changed there.

> "Now I understand, I'll try it and text here if it worked or not"
oki

**Comment by ege-art** [comment]
> > "my ps won't show up until I ping it's ip address"
> 
> 
> 
> Curious, also my script won't update the network interfaces in real time, you need to restart the script if something technically changed there.
> 
> 
> 
> > "Now I understand, I'll try it and text here if it worked or not"
> 
> 
> 
> oki

BTW why is it showing N/A ok the usernames?

**Comment by Illegal-Services** [comment]
> BTW why is it showing N/A on the usernames? 

I assume you've got everything to works correctly now?
It shows N/A because you probably have the blacklist setting enabled, in the blacklist file you can add usernames and their IP, then the program will resolves and color those while sniffing.

**Comment by ege-art** [comment]
> > BTW why is it showing N/A on the usernames? 
> 
> I assume you've got everything to works correctly now?
> It shows N/A because you probably have the blacklist setting enabled, in the blacklist file you can add usernames and their IP, then the program will resolves and color those while sniffing.

Well I only got the usernames to work, not the ARP issue. I didn't have time for that today so I'll try it tomorrow again

**Comment by ege-art** [comment]
🤓
